---
name: Common-Files
version: 1.1
abstract: Test common archive files

X_Module_Faker:
    cpan_author: BORISNAT
    omitted_files:
        - Makefile.PL

    append:
        -
            file: lib/Common/Files.pm
            content: |
                =head1 NAME

                Common::Files - testing common files in a release

                =cut

        -
            file: Makefile.PL
            # NOTE: YAML::Tiny (CPAN::Meta::YAML) strips the blank lines.
            content: |
                print "hi";

                =pod

                some pod

                =cut
