name: IPsonar
version: ""
provides:
    IPsonar:
        file: lib/IPsonar
        version: ~

X_Module_Faker:
    # Version in archive basename but explicitly "" in META.
    archive_basename: IPsonar-0.29

    # Archive::Any::Create (used by Module::Faker) doesn't recognize tgz.
    #archive_ext:      tgz

    omitted_files:
        - META.json
        - META.yml

    append:
        -
            file: lib/IPsonar.pm
            # Module has version like dist name.
            content: |
                package IPsonar;
                our $VERSION;
                $VERSION = "0.29";

        -
            file: META.yml
            content: |
                ---
                abstract: 'a great new dist'
                author:
                    - 'LOCAL <LOCAL@cpan.local>'
                dynamic_config: 0
                license: perl
                meta-spec:
                    url: http://module-build.sourceforge.net/META-spec-v1.4.html
                    version: '1.4'
                name: IPsonar
                version: ''
