---
name: No-Packages
version: 1.1
abstract: An archive with pm files but no parseable packages

# Empty hash so Module::Faker won't build its own.
provides: {}

X_Module_Faker:
    cpan_author: BORISNAT

    append:
        -
            file: NoPackages.pm
            content: |
                use Something;
                # no package statements
