---
name: Build Production Container
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    name: Docker push latest
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: docker build . -t metacpan/metacpan-api:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push build to Docker hub
        run: docker push metacpan/metacpan-api:latest
        if: success() && github.ref == 'refs/heads/master'
