---
name: docker push
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-20.04
    name: Docker
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build . -t metacpan/metacpan-api:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push build to Docker hub
        run: docker push metacpan/metacpan-api:latest
        if: success() && github.ref == 'refs/heads/master'
