name: Update cpanfile.snapshot
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
jobs:
  update-dep:
    runs-on: "ubuntu-20.04"
    container:
      image: perl:5.36
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METACPAN_BOT_TOKEN }}
      - name: Get cpm
        run: |
          curl -sL -o $RUNNER_TEMP/cpm https://git.io/cpm
          chmod +x $RUNNER_TEMP/cpm
      - name: Install deps
        run: >
          $RUNNER_TEMP/cpm
          install
          --cpanfile cpanfile
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
      - name: Maybe update cpanfile.snapshot
        run: perl -Ilocal/lib/perl5 local/bin/carton
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.METACPAN_BOT_TOKEN }}
          commit-message: Update cpanfile.snapshot
          title: Update cpanfile.snapshot
          author: MetaCPAN Bot <bot@metacpan.org>
          committer: MetaCPAN Bot <bot@metacpan.org>
          body: |
            [GitHub Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          push-to-fork: metacpan-bot/metacpan-api
          branch: update-cpanfile-snapshot
