name: Update cpanfile.snapshot
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
jobs:
  update-dep:
    runs-on: "ubuntu-22.04"
    container:
      image: perl:5.36
    steps:
      - name: install jq
        run: |
          sudo apt-get install -y jq
      - name: Generate Auth Token
        id: auth-token
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          jwt: ${{ steps.auth-token.outputs.jwt }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.auth-token.outputs.auth-token }}

      - name: Get cpm
        run: |
          curl -sL -o $RUNNER_TEMP/cpm https://git.io/cpm
          chmod +x $RUNNER_TEMP/cpm
      - name: Install Carton::Snapshot
        run: >
          $RUNNER_TEMP/cpm
          install
          Carton
          Carton::Snapshot
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib=$RUNNER_TEMP/perl5
      - name: Install deps
        run: >
          perl -I$RUNNER_TEMP/perl5/lib/perl5 $RUNNER_TEMP/cpm
          install
          --cpanfile cpanfile
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
      - name: Install deps
        uses: perl-actions/install-with-cpm@stable
        with:
          cpanfile: cpanfile
          sudo: false
          args: >
            --resolver metacpan
            --show-build-log-on-failure
            --local-lib-contained=local
      - name: Maybe update cpanfile.snapshot
        run: carton
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.METACPAN_BOT_TOKEN }}
          commit-message: Update cpanfile.snapshot
          title: Update cpanfile.snapshot
          author: MetaCPAN Bot <bot@metacpan.org>
          committer: MetaCPAN Bot <bot@metacpan.org>
          body: |
            [GitHub Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          push-to-fork: metacpan-bot/metacpan-api
          branch: update-cpanfile-snapshot
